include: package:flutter_lints/flutter.yaml
linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - avoid_print
    - prefer_final_fields
    - prefer_final_locals
    - prefer_const_declarations
    - prefer_const_constructors_in_immutables
    
